2024-12-11 18:23:08,015 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 18:23:08,343 INFO Update id=301615574 is not handled. Duration 333 ms by bot id=7546513983
2024-12-11 18:23:08,343 ERROR Cause exception while process update id=301615574 by bot id=7546513983
HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/%7B%7D/events?timeMin=2024-12-11T18%3A22%3A40Z&timeMax=2024-12-11T18%3A23%3A08Z&singleEvents=true&orderBy=startTime&alt=json returned "Not Found". Details: "[{'domain': 'global', 'reason': 'notFound', 'message': 'Not Found'}]">
Traceback (most recent call last):
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/handlers.py", line 55, in recount
    errors = money_recount()
  File "/Users/matvei/PycharmProjects/testoviy/calendar_myad.py", line 61, in recount
    events_result = service.events().list(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/%7B%7D/events?timeMin=2024-12-11T18%3A22%3A40Z&timeMax=2024-12-11T18%3A23%3A08Z&singleEvents=true&orderBy=startTime&alt=json returned "Not Found". Details: "[{'domain': 'global', 'reason': 'notFound', 'message': 'Not Found'}]">
2024-12-11 18:25:11,881 WARNING Received SIGINT signal
2024-12-11 18:25:11,882 INFO Polling stopped for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 18:25:11,882 INFO Polling stopped
2024-12-11 18:25:17,887 INFO Start polling
2024-12-11 18:25:18,133 INFO Run polling for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 18:25:18,232 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 18:25:18,568 INFO Update id=301615575 is not handled. Duration 344 ms by bot id=7546513983
2024-12-11 18:25:18,568 ERROR Cause exception while process update id=301615575 by bot id=7546513983
HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/%7B%7D/events?timeMin=2024-12-11T18%3A23%3A08Z&timeMax=2024-12-11T18%3A25%3A18Z&singleEvents=true&orderBy=startTime&alt=json returned "Not Found". Details: "[{'domain': 'global', 'reason': 'notFound', 'message': 'Not Found'}]">
Traceback (most recent call last):
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/handlers.py", line 55, in recount
    errors = money_recount()
  File "/Users/matvei/PycharmProjects/testoviy/calendar_myad.py", line 61, in recount
    events_result = service.events().list(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/%7B%7D/events?timeMin=2024-12-11T18%3A23%3A08Z&timeMax=2024-12-11T18%3A25%3A18Z&singleEvents=true&orderBy=startTime&alt=json returned "Not Found". Details: "[{'domain': 'global', 'reason': 'notFound', 'message': 'Not Found'}]">
2024-12-11 18:25:41,048 WARNING Received SIGINT signal
2024-12-11 18:25:41,049 INFO Polling stopped for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 18:25:41,049 INFO Polling stopped
2024-12-11 18:25:46,385 INFO Start polling
2024-12-11 18:25:46,599 INFO Run polling for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 18:25:46,772 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 18:25:47,081 INFO Update id=301615576 is not handled. Duration 313 ms by bot id=7546513983
2024-12-11 18:25:47,081 ERROR Cause exception while process update id=301615576 by bot id=7546513983
HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/%7B%7D/events?timeMin=2024-12-11T18%3A25%3A18Z&timeMax=2024-12-11T18%3A25%3A46Z&singleEvents=true&orderBy=startTime&alt=json returned "Not Found". Details: "[{'domain': 'global', 'reason': 'notFound', 'message': 'Not Found'}]">
Traceback (most recent call last):
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/handlers.py", line 55, in recount
    errors = money_recount()
  File "/Users/matvei/PycharmProjects/testoviy/calendar_myad.py", line 62, in recount
    events_result = service.events().list(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/%7B%7D/events?timeMin=2024-12-11T18%3A25%3A18Z&timeMax=2024-12-11T18%3A25%3A46Z&singleEvents=true&orderBy=startTime&alt=json returned "Not Found". Details: "[{'domain': 'global', 'reason': 'notFound', 'message': 'Not Found'}]">
2024-12-11 18:25:50,275 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 18:25:50,564 INFO Update id=301615577 is not handled. Duration 292 ms by bot id=7546513983
2024-12-11 18:25:50,564 ERROR Cause exception while process update id=301615577 by bot id=7546513983
HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/%7B%7D/events?timeMin=2024-12-11T18%3A25%3A46Z&timeMax=2024-12-11T18%3A25%3A50Z&singleEvents=true&orderBy=startTime&alt=json returned "Not Found". Details: "[{'domain': 'global', 'reason': 'notFound', 'message': 'Not Found'}]">
Traceback (most recent call last):
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/handlers.py", line 55, in recount
    errors = money_recount()
  File "/Users/matvei/PycharmProjects/testoviy/calendar_myad.py", line 62, in recount
    events_result = service.events().list(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/%7B%7D/events?timeMin=2024-12-11T18%3A25%3A46Z&timeMax=2024-12-11T18%3A25%3A50Z&singleEvents=true&orderBy=startTime&alt=json returned "Not Found". Details: "[{'domain': 'global', 'reason': 'notFound', 'message': 'Not Found'}]">
2024-12-11 18:26:38,567 WARNING Received SIGINT signal
2024-12-11 18:26:38,567 INFO Polling stopped for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 18:26:38,568 INFO Polling stopped
2024-12-11 18:26:44,119 INFO Start polling
2024-12-11 18:26:44,339 INFO Run polling for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 18:26:44,437 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 18:26:44,758 INFO Update id=301615578 is not handled. Duration 324 ms by bot id=7546513983
2024-12-11 18:26:44,758 ERROR Cause exception while process update id=301615578 by bot id=7546513983
HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/%7B%7D/events?timeMin=2024-12-11T18%3A25%3A50Z&timeMax=2024-12-11T18%3A26%3A44Z&singleEvents=true&orderBy=startTime&alt=json returned "Not Found". Details: "[{'domain': 'global', 'reason': 'notFound', 'message': 'Not Found'}]">
Traceback (most recent call last):
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/handlers.py", line 55, in recount
    errors = money_recount()
  File "/Users/matvei/PycharmProjects/testoviy/calendar_myad.py", line 63, in recount
    events_result = service.events().list(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/%7B%7D/events?timeMin=2024-12-11T18%3A25%3A50Z&timeMax=2024-12-11T18%3A26%3A44Z&singleEvents=true&orderBy=startTime&alt=json returned "Not Found". Details: "[{'domain': 'global', 'reason': 'notFound', 'message': 'Not Found'}]">
2024-12-11 18:26:50,376 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 18:26:50,664 INFO Update id=301615579 is not handled. Duration 291 ms by bot id=7546513983
2024-12-11 18:26:50,664 ERROR Cause exception while process update id=301615579 by bot id=7546513983
HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/%7B%7D/events?timeMin=2024-12-11T18%3A26%3A44Z&timeMax=2024-12-11T18%3A26%3A50Z&singleEvents=true&orderBy=startTime&alt=json returned "Not Found". Details: "[{'domain': 'global', 'reason': 'notFound', 'message': 'Not Found'}]">
Traceback (most recent call last):
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/handlers.py", line 55, in recount
    errors = money_recount()
  File "/Users/matvei/PycharmProjects/testoviy/calendar_myad.py", line 63, in recount
    events_result = service.events().list(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/%7B%7D/events?timeMin=2024-12-11T18%3A26%3A44Z&timeMax=2024-12-11T18%3A26%3A50Z&singleEvents=true&orderBy=startTime&alt=json returned "Not Found". Details: "[{'domain': 'global', 'reason': 'notFound', 'message': 'Not Found'}]">
2024-12-11 18:27:17,739 WARNING Received SIGINT signal
2024-12-11 18:27:17,740 INFO Polling stopped for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 18:27:17,740 INFO Polling stopped
2024-12-11 18:27:22,456 INFO Start polling
2024-12-11 18:27:22,675 INFO Run polling for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 18:27:22,768 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 18:27:23,039 INFO Update id=301615580 is not handled. Duration 275 ms by bot id=7546513983
2024-12-11 18:27:23,039 ERROR Cause exception while process update id=301615580 by bot id=7546513983
HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/%7B%7D/events?timeMin=2024-12-11T18%3A26%3A50Z&timeMax=2024-12-11T18%3A27%3A22Z&singleEvents=true&orderBy=startTime&alt=json returned "Not Found". Details: "[{'domain': 'global', 'reason': 'notFound', 'message': 'Not Found'}]">
Traceback (most recent call last):
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/handlers.py", line 55, in recount
    errors = money_recount()
  File "/Users/matvei/PycharmProjects/testoviy/calendar_myad.py", line 64, in recount
    events_result = service.events().list(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/%7B%7D/events?timeMin=2024-12-11T18%3A26%3A50Z&timeMax=2024-12-11T18%3A27%3A22Z&singleEvents=true&orderBy=startTime&alt=json returned "Not Found". Details: "[{'domain': 'global', 'reason': 'notFound', 'message': 'Not Found'}]">
2024-12-11 18:29:14,849 WARNING Received SIGINT signal
2024-12-11 18:29:14,850 INFO Polling stopped for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 18:29:14,850 INFO Polling stopped
2024-12-11 18:29:20,000 INFO Start polling
2024-12-11 18:29:20,234 INFO Run polling for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 18:29:20,341 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 18:29:20,678 INFO Update id=301615581 is not handled. Duration 344 ms by bot id=7546513983
2024-12-11 18:29:20,679 ERROR Cause exception while process update id=301615581 by bot id=7546513983
HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/%7B%7D/events?timeMin=2024-12-11T18%3A27%3A22Z&timeMax=2024-12-11T18%3A29%3A20Z&singleEvents=true&orderBy=startTime&alt=json returned "Not Found". Details: "[{'domain': 'global', 'reason': 'notFound', 'message': 'Not Found'}]">
Traceback (most recent call last):
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/handlers.py", line 55, in recount
    errors = money_recount()
  File "/Users/matvei/PycharmProjects/testoviy/calendar_myad.py", line 63, in recount
    events_result = service.events().list(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/%7B%7D/events?timeMin=2024-12-11T18%3A27%3A22Z&timeMax=2024-12-11T18%3A29%3A20Z&singleEvents=true&orderBy=startTime&alt=json returned "Not Found". Details: "[{'domain': 'global', 'reason': 'notFound', 'message': 'Not Found'}]">
2024-12-11 18:30:31,389 WARNING Received SIGINT signal
2024-12-11 18:30:31,390 INFO Polling stopped for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 18:30:31,391 INFO Polling stopped
2024-12-11 18:30:49,810 INFO Start polling
2024-12-11 18:30:50,043 INFO Run polling for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 18:30:50,130 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 18:30:50,464 INFO Update id=301615582 is not handled. Duration 340 ms by bot id=7546513983
2024-12-11 18:30:50,464 ERROR Cause exception while process update id=301615582 by bot id=7546513983
HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/%7B%7D/events?timeMin=2024-12-11T18%3A29%3A20Z&timeMax=2024-12-11T18%3A30%3A50Z&singleEvents=true&orderBy=startTime&alt=json returned "Not Found". Details: "[{'domain': 'global', 'reason': 'notFound', 'message': 'Not Found'}]">
Traceback (most recent call last):
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/handlers.py", line 55, in recount
    errors = money_recount()
  File "/Users/matvei/PycharmProjects/testoviy/calendar_myad.py", line 64, in recount
    events_result = service.events().list(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/%7B%7D/events?timeMin=2024-12-11T18%3A29%3A20Z&timeMax=2024-12-11T18%3A30%3A50Z&singleEvents=true&orderBy=startTime&alt=json returned "Not Found". Details: "[{'domain': 'global', 'reason': 'notFound', 'message': 'Not Found'}]">
2024-12-11 18:32:27,749 WARNING Received SIGINT signal
2024-12-11 18:32:27,750 INFO Polling stopped for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 18:32:27,750 INFO Polling stopped
2024-12-11 18:32:33,092 INFO Start polling
2024-12-11 18:32:33,722 INFO Run polling for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 18:32:33,810 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 18:32:34,511 INFO Update id=301615583 is handled. Duration 705 ms by bot id=7546513983
2024-12-11 18:33:31,515 WARNING Received SIGINT signal
2024-12-11 18:33:31,516 INFO Polling stopped for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 18:33:31,516 INFO Polling stopped
2024-12-11 18:33:37,411 INFO Start polling
2024-12-11 18:33:37,654 INFO Run polling for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 18:33:37,742 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 18:33:38,109 INFO Update id=301615584 is handled. Duration 373 ms by bot id=7546513983
2024-12-11 18:33:49,145 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 18:33:49,498 INFO Update id=301615585 is handled. Duration 355 ms by bot id=7546513983
2024-12-11 18:34:34,625 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 18:34:34,980 INFO Update id=301615586 is handled. Duration 359 ms by bot id=7546513983
2024-12-11 18:37:26,476 WARNING Received SIGINT signal
2024-12-11 18:37:26,477 INFO Polling stopped for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 18:37:26,477 INFO Polling stopped
2024-12-11 18:37:31,728 INFO Start polling
2024-12-11 18:37:31,966 INFO Run polling for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 18:37:37,849 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 18:37:38,248 INFO Update id=301615587 is handled. Duration 410 ms by bot id=7546513983
2024-12-11 18:41:19,416 WARNING Received SIGINT signal
2024-12-11 18:41:19,417 INFO Polling stopped for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 18:41:19,417 INFO Polling stopped
2024-12-11 18:41:24,764 INFO Start polling
2024-12-11 18:41:25,003 INFO Run polling for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 18:41:26,813 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 18:41:27,651 INFO Update id=301615588 is handled. Duration 848 ms by bot id=7546513983
2024-12-11 18:42:19,145 WARNING Received SIGINT signal
2024-12-11 18:42:19,146 INFO Polling stopped for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 18:42:19,146 INFO Polling stopped
2024-12-11 18:50:16,769 INFO Start polling
2024-12-11 18:50:17,009 INFO Run polling for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 18:50:17,101 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 18:50:17,495 ERROR НЕПРАВИЛЬНЫЙ ФОРМАТ ОПИСАНИЯ!
 урок Бейз;
 Дата занятия: 2024-12-08T01:15:00+03:00;
 Описание - 124512asdasda
2024-12-11 18:50:18,029 INFO Update id=301615589 is handled. Duration 934 ms by bot id=7546513983
2024-12-11 18:50:34,436 INFO Update id=301615590 is handled. Duration 230 ms by bot id=7546513983
2024-12-11 18:50:40,552 INFO Update id=301615591 is handled. Duration 85 ms by bot id=7546513983
2024-12-11 18:50:44,779 INFO Update id=301615592 is handled. Duration 145 ms by bot id=7546513983
2024-12-11 18:50:46,715 INFO Update id=301615593 is handled. Duration 129 ms by bot id=7546513983
2024-12-11 18:50:48,819 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 18:50:49,229 INFO Нет предстоящих событий.


2024-12-11 18:50:49,558 INFO Update id=301615594 is handled. Duration 743 ms by bot id=7546513983
2024-12-11 18:51:20,906 INFO Update id=301615595 is handled. Duration 266 ms by bot id=7546513983
2024-12-11 18:51:23,165 INFO Update id=301615596 is handled. Duration 155 ms by bot id=7546513983
2024-12-11 19:13:08,878 WARNING Received SIGINT signal
2024-12-11 19:13:08,880 INFO Polling stopped for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 19:13:08,881 INFO Polling stopped
2024-12-11 19:13:14,504 INFO Start polling
2024-12-11 19:13:14,782 INFO Run polling for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 19:13:15,173 INFO Update id=301615597 is handled. Duration 309 ms by bot id=7546513983
2024-12-11 19:13:17,833 INFO Update id=301615598 is handled. Duration 89 ms by bot id=7546513983
2024-12-11 19:13:19,824 INFO Update id=301615599 is handled. Duration 95 ms by bot id=7546513983
2024-12-11 19:13:21,409 INFO Update id=301615600 is handled. Duration 112 ms by bot id=7546513983
2024-12-11 19:13:44,471 INFO Update id=301615601 is handled. Duration 282 ms by bot id=7546513983
2024-12-11 19:13:52,812 INFO Update id=301615602 is handled. Duration 165 ms by bot id=7546513983
2024-12-11 19:14:00,974 INFO Update id=301615603 is handled. Duration 165 ms by bot id=7546513983
2024-12-11 19:16:31,728 WARNING Received SIGINT signal
2024-12-11 19:16:31,729 INFO Polling stopped for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 19:16:31,729 INFO Polling stopped
2024-12-11 19:16:38,557 INFO Start polling
2024-12-11 19:16:38,814 INFO Run polling for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 19:16:39,287 INFO Update id=301615604 is handled. Duration 395 ms by bot id=7546513983
2024-12-11 19:16:42,734 INFO Update id=301615605 is handled. Duration 81 ms by bot id=7546513983
2024-12-11 19:16:44,495 INFO Update id=301615606 is handled. Duration 90 ms by bot id=7546513983
2024-12-11 19:30:02,138 WARNING Received SIGINT signal
2024-12-11 19:30:02,140 INFO Polling stopped for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 19:30:02,140 INFO Polling stopped
2024-12-11 19:30:45,020 INFO Start polling
2024-12-11 19:30:45,276 INFO Run polling for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 19:32:30,527 WARNING Received SIGINT signal
2024-12-11 19:32:30,527 INFO Polling stopped for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 19:32:30,528 INFO Polling stopped
2024-12-11 19:32:36,454 INFO Start polling
2024-12-11 19:32:36,672 INFO Run polling for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 19:32:37,044 INFO Update id=301615607 is handled. Duration 251 ms by bot id=7546513983
2024-12-11 19:32:47,152 INFO Update id=301615608 is handled. Duration 82 ms by bot id=7546513983
2024-12-11 19:33:01,659 INFO Update id=301615609 is handled. Duration 89 ms by bot id=7546513983
2024-12-11 19:33:08,339 INFO Update id=301615610 is handled. Duration 85 ms by bot id=7546513983
2024-12-11 19:33:26,433 INFO Update id=301615611 is not handled. Duration 3 ms by bot id=7546513983
2024-12-11 19:33:26,434 ERROR Cause exception while process update id=301615611 by bot id=7546513983
ValueError: invalid literal for int() with base 10: '100песо'
Traceback (most recent call last):
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/handlers.py", line 201, in add_new_price
    await state.update_data(price=int(message.text))
ValueError: invalid literal for int() with base 10: '100песо'
2024-12-11 19:33:31,496 INFO Update id=301615612 is not handled. Duration 2 ms by bot id=7546513983
2024-12-11 19:33:31,496 ERROR Cause exception while process update id=301615612 by bot id=7546513983
ValueError: invalid literal for int() with base 10: '/check'
Traceback (most recent call last):
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/handlers.py", line 201, in add_new_price
    await state.update_data(price=int(message.text))
ValueError: invalid literal for int() with base 10: '/check'
2024-12-11 19:33:37,918 WARNING Received SIGINT signal
2024-12-11 19:33:37,919 INFO Polling stopped for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 19:33:37,919 INFO Polling stopped
2024-12-11 19:35:57,881 INFO Start polling
2024-12-11 19:35:58,147 INFO Run polling for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 19:35:58,556 INFO Update id=301615613 is handled. Duration 321 ms by bot id=7546513983
2024-12-11 19:36:00,938 INFO Update id=301615614 is handled. Duration 178 ms by bot id=7546513983
2024-12-11 19:36:06,060 INFO Update id=301615615 is handled. Duration 125 ms by bot id=7546513983
2024-12-11 19:36:08,994 INFO Update id=301615616 is handled. Duration 196 ms by bot id=7546513983
2024-12-11 19:36:11,620 INFO Update id=301615617 is not handled. Duration 1 ms by bot id=7546513983
2024-12-11 19:36:13,322 INFO Update id=301615618 is handled. Duration 117 ms by bot id=7546513983
2024-12-11 19:36:15,685 INFO Update id=301615619 is handled. Duration 116 ms by bot id=7546513983
2024-12-11 19:36:23,427 INFO Update id=301615620 is handled. Duration 121 ms by bot id=7546513983
2024-12-11 19:36:25,620 INFO Update id=301615621 is handled. Duration 106 ms by bot id=7546513983
2024-12-11 19:36:36,124 INFO Update id=301615622 is not handled. Duration 3 ms by bot id=7546513983
2024-12-11 19:36:45,853 INFO Update id=301615623 is not handled. Duration 2 ms by bot id=7546513983
2024-12-11 19:37:22,694 WARNING Received SIGINT signal
2024-12-11 19:37:22,695 INFO Polling stopped for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 19:37:22,695 INFO Polling stopped
2024-12-11 19:37:27,316 INFO Start polling
2024-12-11 19:37:27,540 INFO Run polling for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 19:37:29,483 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 19:37:29,870 ERROR НЕПРАВИЛЬНЫЙ ФОРМАТ ОПИСАНИЯ!
 урок Бейз;
 Дата занятия: 2024-12-08T01:15:00+03:00;
 Описание - 124512asdasda
2024-12-11 19:37:30,301 INFO Update id=301615624 is handled. Duration 1115 ms by bot id=7546513983
2024-12-11 19:41:10,853 WARNING Received SIGINT signal
2024-12-11 19:41:10,854 INFO Polling stopped for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 19:41:10,854 INFO Polling stopped
2024-12-11 19:44:05,508 INFO Start polling
2024-12-11 19:44:05,732 INFO Run polling for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 19:44:12,035 INFO Update id=301615625 is handled. Duration 277 ms by bot id=7546513983
2024-12-11 19:44:14,936 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 19:44:15,328 ERROR НЕПРАВИЛЬНЫЙ ФОРМАТ ОПИСАНИЯ!
 Бейз урок;
 Дата занятия: 2024-12-08T01:15:00+03:00;
 Описание - 124512asdasda
2024-12-11 19:44:15,550 INFO Update id=301615626 is handled. Duration 624 ms by bot id=7546513983
2024-12-11 19:44:41,689 INFO Update id=301615627 is handled. Duration 496 ms by bot id=7546513983
2024-12-11 19:44:45,529 INFO Update id=301615628 is handled. Duration 250 ms by bot id=7546513983
2024-12-11 19:44:47,479 INFO Update id=301615629 is handled. Duration 124 ms by bot id=7546513983
2024-12-11 19:45:07,545 WARNING Received SIGINT signal
2024-12-11 19:45:07,546 INFO Polling stopped for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 19:45:07,546 INFO Polling stopped
