2024-12-11 01:17:13,283 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 01:17:13,645 INFO Update id=301615514 is not handled. Duration 377 ms by bot id=7546513983
2024-12-11 01:17:13,646 ERROR Cause exception while process update id=301615514 by bot id=7546513983
HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/%7B%7D/events?timeMin=2024-12-11T01%3A15%3A20Z&timeMax=2024-12-11T01%3A17%3A13Z&singleEvents=true&orderBy=startTime&alt=json returned "Not Found". Details: "[{'domain': 'global', 'reason': 'notFound', 'message': 'Not Found'}]">
Traceback (most recent call last):
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/handlers.py", line 55, in recount
    errors = money_recount()
  File "/Users/matvei/PycharmProjects/testoviy/calendar_myad.py", line 44, in recount
    events_result = service.events().list(calendarId=configjson["calendarid"], timeMin=from_date, timeMax=to_date,
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/calendar/v3/calendars/%7B%7D/events?timeMin=2024-12-11T01%3A15%3A20Z&timeMax=2024-12-11T01%3A17%3A13Z&singleEvents=true&orderBy=startTime&alt=json returned "Not Found". Details: "[{'domain': 'global', 'reason': 'notFound', 'message': 'Not Found'}]">
2024-12-11 01:18:05,445 WARNING Received SIGINT signal
2024-12-11 01:18:05,446 INFO Polling stopped for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 01:18:05,446 INFO Polling stopped
2024-12-11 01:18:12,896 INFO Start polling
2024-12-11 01:18:13,127 INFO Run polling for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 01:18:13,215 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 01:18:14,178 INFO Update id=301615515 is not handled. Duration 968 ms by bot id=7546513983
2024-12-11 01:18:14,178 ERROR Cause exception while process update id=301615515 by bot id=7546513983
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/handlers.py", line 63, in recount
    if len(errors) != 0:
TypeError: object of type 'NoneType' has no len()
2024-12-11 01:18:25,121 INFO Update id=301615516 is handled. Duration 75 ms by bot id=7546513983
2024-12-11 01:18:29,339 INFO Update id=301615517 is handled. Duration 74 ms by bot id=7546513983
2024-12-11 01:18:31,839 INFO Update id=301615518 is handled. Duration 82 ms by bot id=7546513983
2024-12-11 01:18:33,663 INFO Update id=301615519 is handled. Duration 116 ms by bot id=7546513983
2024-12-11 01:18:35,322 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 01:18:36,109 INFO Update id=301615520 is not handled. Duration 789 ms by bot id=7546513983
2024-12-11 01:18:36,110 ERROR Cause exception while process update id=301615520 by bot id=7546513983
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/handlers.py", line 63, in recount
    if len(errors) != 0:
TypeError: object of type 'NoneType' has no len()
2024-12-11 01:18:44,779 INFO Update id=301615521 is handled. Duration 77 ms by bot id=7546513983
2024-12-11 01:18:50,974 INFO Update id=301615522 is handled. Duration 124 ms by bot id=7546513983
2024-12-11 01:18:54,430 INFO Update id=301615523 is handled. Duration 97 ms by bot id=7546513983
2024-12-11 01:18:55,744 INFO Update id=301615524 is handled. Duration 160 ms by bot id=7546513983
2024-12-11 01:18:58,258 INFO Update id=301615525 is not handled. Duration 1 ms by bot id=7546513983
2024-12-11 01:18:59,168 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 01:19:00,507 INFO Update id=301615526 is not handled. Duration 1341 ms by bot id=7546513983
2024-12-11 01:19:00,507 ERROR Cause exception while process update id=301615526 by bot id=7546513983
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/handlers.py", line 63, in recount
    if len(errors) != 0:
TypeError: object of type 'NoneType' has no len()
2024-12-11 01:19:02,526 INFO Update id=301615527 is handled. Duration 97 ms by bot id=7546513983
2024-12-11 01:19:07,531 INFO Update id=301615528 is handled. Duration 137 ms by bot id=7546513983
2024-12-11 01:19:10,150 INFO Update id=301615529 is not handled. Duration 1 ms by bot id=7546513983
2024-12-11 01:19:11,128 INFO Update id=301615530 is not handled. Duration 1 ms by bot id=7546513983
2024-12-11 01:19:13,236 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 01:19:14,012 INFO Update id=301615531 is not handled. Duration 778 ms by bot id=7546513983
2024-12-11 01:19:14,012 ERROR Cause exception while process update id=301615531 by bot id=7546513983
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/handlers.py", line 63, in recount
    if len(errors) != 0:
TypeError: object of type 'NoneType' has no len()
2024-12-11 01:19:26,005 INFO Update id=301615532 is handled. Duration 68 ms by bot id=7546513983
2024-12-11 01:19:30,981 INFO Update id=301615533 is handled. Duration 107 ms by bot id=7546513983
2024-12-11 01:19:34,599 INFO Update id=301615534 is handled. Duration 81 ms by bot id=7546513983
2024-12-11 01:19:37,367 INFO Update id=301615535 is handled. Duration 77 ms by bot id=7546513983
2024-12-11 01:19:39,043 INFO Update id=301615536 is handled. Duration 79 ms by bot id=7546513983
2024-12-11 01:19:42,608 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 01:19:43,727 INFO Update id=301615537 is not handled. Duration 1122 ms by bot id=7546513983
2024-12-11 01:19:43,728 ERROR Cause exception while process update id=301615537 by bot id=7546513983
TypeError: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/handlers.py", line 63, in recount
    if len(errors) != 0:
TypeError: object of type 'NoneType' has no len()
2024-12-11 01:19:48,744 INFO Update id=301615538 is handled. Duration 69 ms by bot id=7546513983
2024-12-11 01:19:52,475 INFO Update id=301615539 is handled. Duration 113 ms by bot id=7546513983
2024-12-11 01:19:54,459 INFO Update id=301615540 is handled. Duration 88 ms by bot id=7546513983
2024-12-11 01:19:55,815 INFO Update id=301615541 is handled. Duration 116 ms by bot id=7546513983
2024-12-11 01:20:03,587 INFO Update id=301615542 is handled. Duration 181 ms by bot id=7546513983
2024-12-11 01:22:28,929 WARNING Received SIGINT signal
2024-12-11 01:22:28,931 INFO Polling stopped for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 01:22:28,931 INFO Polling stopped
2024-12-11 01:22:34,399 INFO Start polling
2024-12-11 01:22:34,691 INFO Run polling for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 01:22:53,433 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 01:22:53,795 ERROR НЕПРАВИЛЬНЫЙ ФОРМАТ ОПИСАНИЯ! Бейз; Дата занятия: 2024-11-25T00:30:00+03:00; Описание - Нет описания
2024-12-11 01:22:56,090 INFO Update id=301615543 is not handled. Duration 2667 ms by bot id=7546513983
2024-12-11 01:22:56,090 ERROR Cause exception while process update id=301615543 by bot id=7546513983
TelegramBadRequest: Telegram server says - Bad Request: text must be non-empty
Traceback (most recent call last):
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/handlers.py", line 66, in recount
    await message.answer(i)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/methods/base.py", line 84, in emit
    return await bot(self)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/client/bot.py", line 494, in __call__
    return await self.session(self, method, timeout=request_timeout)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/client/session/base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/client/session/aiohttp.py", line 189, in make_request
    response = self.check_response(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/client/session/base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: text must be non-empty
2024-12-11 01:23:53,199 WARNING Received SIGINT signal
2024-12-11 01:23:53,200 INFO Polling stopped for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 01:23:53,200 INFO Polling stopped
2024-12-11 01:23:59,824 INFO Start polling
2024-12-11 01:24:00,077 INFO Run polling for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 01:24:13,883 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 01:24:14,225 ERROR НЕПРАВИЛЬНЫЙ ФОРМАТ ОПИСАНИЯ! Бейз; Дата занятия: 2024-11-25T00:30:00+03:00; Описание - Нет описания
2024-12-11 01:24:14,933 INFO Update id=301615544 is handled. Duration 1061 ms by bot id=7546513983
2024-12-11 01:24:31,647 WARNING Received SIGINT signal
2024-12-11 01:24:31,648 INFO Polling stopped for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 01:24:31,648 INFO Polling stopped
2024-12-11 01:26:04,915 INFO Start polling
2024-12-11 01:26:05,139 INFO Run polling for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 01:26:05,236 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 01:26:06,297 INFO Update id=301615545 is handled. Duration 1067 ms by bot id=7546513983
2024-12-11 01:27:15,522 WARNING Received SIGINT signal
2024-12-11 01:27:15,523 INFO Polling stopped for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 01:27:15,524 INFO Polling stopped
2024-12-11 01:27:23,211 INFO Start polling
2024-12-11 01:27:23,439 INFO Run polling for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 01:27:23,555 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 01:27:24,479 INFO Update id=301615546 is handled. Duration 934 ms by bot id=7546513983
2024-12-11 01:27:36,506 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 01:27:36,916 INFO Update id=301615547 is not handled. Duration 414 ms by bot id=7546513983
2024-12-11 01:27:36,916 ERROR Cause exception while process update id=301615547 by bot id=7546513983
UnboundLocalError: local variable 'i' referenced before assignment
Traceback (most recent call last):
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/fsm/middleware.py", line 42, in __call__
    return await handler(event, data)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 174, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 141, in _wrapped
    return await self._propagate_event(
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/matvei/PycharmProjects/testoviy/.venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/Users/matvei/PycharmProjects/testoviy/handlers.py", line 55, in recount
    errors = money_recount()
  File "/Users/matvei/PycharmProjects/testoviy/calendar_myad.py", line 84, in recount
    f'НЕПРАВИЛЬНЫЙ ФОРМАТ ОПИСАНИЯ!\n {summary};\n {i};\n Дата занятия: {eventstart};\n Описание - {description}\n\n')
UnboundLocalError: local variable 'i' referenced before assignment
2024-12-11 01:28:29,601 WARNING Received SIGINT signal
2024-12-11 01:28:29,602 INFO Polling stopped for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 01:28:29,602 INFO Polling stopped
2024-12-11 01:28:37,181 INFO Start polling
2024-12-11 01:28:37,459 INFO Run polling for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 01:28:43,702 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 01:28:43,990 ERROR НЕПРАВИЛЬНЫЙ ФОРМАТ ОПИСАНИЯ!
 Бейз;
 Дата занятия: 2024-11-25T00:30:00+03:00;
 Описание - Нет описания
2024-12-11 01:28:44,733 INFO Update id=301615548 is handled. Duration 1038 ms by bot id=7546513983
2024-12-11 01:29:27,568 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 01:29:27,906 INFO Update id=301615549 is handled. Duration 340 ms by bot id=7546513983
2024-12-11 01:29:48,016 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 01:29:48,401 ERROR НЕПРАВИЛЬНЫЙ ФОРМАТ ОПИСАНИЯ!
 Бейз;
 Дата занятия: 2024-11-25T00:30:00+03:00;
 Описание - Нет описания
2024-12-11 01:29:48,695 INFO Update id=301615550 is handled. Duration 684 ms by bot id=7546513983
2024-12-11 01:29:57,748 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 01:29:58,168 INFO Update id=301615551 is handled. Duration 422 ms by bot id=7546513983
2024-12-11 01:31:12,969 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 01:31:13,292 ERROR НЕПРАВИЛЬНЫЙ ФОРМАТ ОПИСАНИЯ!
 Бейз;
 Дата занятия: 2024-11-25T00:30:00+03:00;
 Описание - Нет описания
2024-12-11 01:31:13,644 INFO Update id=301615552 is handled. Duration 678 ms by bot id=7546513983
2024-12-11 01:32:37,232 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 01:32:37,557 ERROR НЕПРАВИЛЬНЫЙ ФОРМАТ ОПИСАНИЯ!
 Бейз;
 Дата занятия: 2024-11-25T00:30:00+03:00;
 Описание - Нет описания
2024-12-11 01:32:37,888 INFO Update id=301615553 is handled. Duration 661 ms by bot id=7546513983
2024-12-11 01:32:40,430 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 01:32:40,863 INFO Update id=301615554 is handled. Duration 433 ms by bot id=7546513983
2024-12-11 01:34:47,962 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 01:34:48,504 INFO Update id=301615555 is handled. Duration 544 ms by bot id=7546513983
2024-12-11 01:35:32,361 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 01:35:32,686 INFO Update id=301615556 is handled. Duration 327 ms by bot id=7546513983
2024-12-11 01:35:46,343 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 01:35:46,674 ERROR НЕПРАВИЛЬНЫЙ ФОРМАТ ОПИСАНИЯ!
 Бейз;
 Дата занятия: 2024-11-25T00:30:00+03:00;
 Описание - Нет описания
2024-12-11 01:35:46,969 INFO Update id=301615557 is handled. Duration 630 ms by bot id=7546513983
2024-12-11 01:37:59,044 WARNING Received SIGINT signal
2024-12-11 01:37:59,044 INFO Polling stopped for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 01:37:59,045 INFO Polling stopped
2024-12-11 01:38:05,517 INFO Start polling
2024-12-11 01:38:05,745 INFO Run polling for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 01:38:24,873 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 01:38:25,449 INFO Update id=301615558 is handled. Duration 584 ms by bot id=7546513983
2024-12-11 01:38:27,187 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 01:38:27,488 INFO Update id=301615559 is handled. Duration 304 ms by bot id=7546513983
2024-12-11 01:38:29,571 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 01:38:29,901 INFO Update id=301615560 is handled. Duration 333 ms by bot id=7546513983
2024-12-11 01:39:21,035 WARNING Received SIGINT signal
2024-12-11 01:39:21,036 INFO Polling stopped for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 01:39:21,037 INFO Polling stopped
2024-12-11 01:39:27,478 INFO Start polling
2024-12-11 01:39:27,705 INFO Run polling for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 01:39:27,794 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 01:39:28,122 INFO Update id=301615561 is handled. Duration 335 ms by bot id=7546513983
2024-12-11 01:41:03,635 WARNING Received SIGINT signal
2024-12-11 01:41:03,636 INFO Polling stopped for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 01:41:03,636 INFO Polling stopped
2024-12-11 01:42:26,912 INFO Start polling
2024-12-11 01:42:27,131 INFO Run polling for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 01:42:29,974 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 01:42:30,292 INFO Update id=301615562 is handled. Duration 325 ms by bot id=7546513983
2024-12-11 01:42:40,648 INFO file_cache is only supported with oauth2client<4.0.0
2024-12-11 01:42:41,220 INFO Update id=301615563 is handled. Duration 573 ms by bot id=7546513983
2024-12-11 01:44:08,183 WARNING Received SIGINT signal
2024-12-11 01:44:08,183 INFO Polling stopped for bot @matveykalobot id=7546513983 - 'великий бот матвейки'
2024-12-11 01:44:08,184 INFO Polling stopped
